version: "3.7"

services:
  jenkins:
    image: "jenkins/jenkins"
    restart: unless-stopped
    user: root
    ports:
      - "9090:8080"
    privileged: true
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    container_name: "jenkins"
